// File generated by FlutterFire CLI / Manual Configuration for Package: com.fanmining.app
import 'package:firebase_core/firebase_core me.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Pre-configured options for existing com.fanmining.app Android Project
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_EXISTING_ANDROID_API_KEY',
    appId: '1:100000000000:android:abcdef0123456789',
    messagingSenderId: '100000000000',
    projectId: 'fan-mining-app',
    storageBucket: 'fan-mining-app.appspot.com',
  );
}
